# Site settings
title: Jesse Grushack
description: My site. It's tight. 
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jesse Grushack
user_description: I\'m an Entrepreneur, always searching for the next challenge; looking at problems from new perspectives. I know a lot about music tech, festivals, crypto, and project management. 
user_title: Me
email: JGrushack@gmail.com
twitter_username: JesseGrushack
github_username:  JGrushack
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
